@startuml

left to right direction
skinparam linetype ortho

class Booking {
  - id: Long <<generated>>
  --
  - customerName: String
  - from: LocalDate
  - to: LocalDate
  - car: Car
}
class Car {
  - id: Long <<generated>>
  --
  - name: String
  - literPer100Km: double
  - yyyy: int
  - origin: String
}

Car "1" <-- "*" Booking
@enduml
