@startuml



left to right direction
skinparam linetype ortho

class Booking {
  - customerName: String
  - from: LocalDate
  - id: Long
  - car: Car
  - to: LocalDate
}
class Car {
  - literPer100Km: double
  - weightInKg: int
  - cylinders: int
  + LBS_TO_KG_CONVERSION_FACTOR: double
  + MILES_TO_KM_CONVERSION_FACTOR: double
  - displacementCc: int
  + GALLON_TO_LITER_CONVERSION_FACTOR: double
  - origin: String
  - id: Long
  - yyyy: int
  - accelerationTo100Kmph: int
  + CONVERSION_MULTIPLIER: Map<String, Double>
  - horsepower: int
  + MPG_TO_LITERPERKM_CONVERSION_FACTOR: double
  - name: String
}

Booking "1" *-[#595959,plain]-> "car\n1" Car
@enduml
